# -*- coding: utf-8 -*-
"""Capstone Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stb2dWtuAAhv2_pJxq31eoInlBVbTbFz

##Phase 1: Data Collection & Understanding
"""

# Importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the retail sales dataset
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("SampleSuperstore.csv", encoding='latin1')

# Displaying first 5 rows of dataset
df.head()

# Checking number of rows and columns in dataset
df.shape

# Checking all columns in datset
df.columns

# Understanding dataset structure and datatypes
df.info()

# Generating statistical summary of numerical columns
df.describe()

"""##Phase 2: Data Cleaning & Preparation"""

# Checking for missing values in dataset
df.isnull().sum()

# Checking duplicate records in dataset
df.duplicated().sum()

# Standardizing column names for better readability
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.replace('-', '_')
df.columns

# Converting date columns into datetime format
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

# Creating additional columns for time-based analysis
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()

# Calculating profit margin percentage
df['profit_margin'] = (df['profit'] / df['sales']) * 100

df.head()

df.info()

"""##PHASE 3 — EXPLORATORY DATA ANALYSIS (EDA)

###SECTION 1 — SALES ANALYSIS

1. Monthly Sales Trend

"""

# Analysing monthly sales trend
monthly_sales = df.groupby('order_month')['sales'].sum().reset_index()

monthly_sales

# Visualization
plt.figure(figsize=(10,5))

plt.plot(monthly_sales['order_month'],
         monthly_sales['sales'],
         marker='o')

plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Sales')

plt.grid(True)

plt.show()

"""Insights:
- Sales fluctuate across different months.
- Some months show significantly higher sales indicating seasonal demand.
- Business experiences peak sales during festive or high-demand periods.

2. Top-Selling Products
"""

# Identifying top-selling products based on sales revenue
top_products = df.groupby('product_name')['sales'].sum().sort_values(ascending=False).head(10)

top_products

#Visualization
top_products.plot(kind='barh', figsize=(10,6))

plt.title('Top 10 Selling Products')
plt.xlabel('Sales')
plt.ylabel('Products')

plt.show()

"""Insights:
- A few products contribute major portion of total revenue.
- High-performing products should be promoted more aggressively.
- Inventory of best-selling products should be maintained properly.

3. Region-wise Revenue
"""

# Analysing revenue generated across different regions
region_sales = df.groupby('region')['sales'].sum()

region_sales

#Visualization
region_sales.plot(kind='bar', figsize=(8,5))

plt.title('Region-wise Revenue')
plt.xlabel('Region')
plt.ylabel('Sales')

plt.show()

"""Insights:
- Certain regions contribute higher sales compared to others.
- Low-performing regions may require additional marketing strategies.
- Regional analysis helps management allocate resources effectively.

4. Profit Margin Analysis
"""

# Analysing average profit margin by category
avg_profit_margin = df.groupby('category')['profit_margin'].mean()

avg_profit_margin

#Visualization
avg_profit_margin.plot(kind='bar', figsize=(8,5))

plt.title('Average Profit Margin by Category')
plt.xlabel('Category')
plt.ylabel('Profit Margin')

plt.show()

"""Insights:
- Some product categories generate higher profit margins.
- Categories with low or negative margins need pricing review.
- Profitability analysis helps improve business decisions.

###SECTION 2 — CUSTOMER ANALYSIS
5. New vs Repeat Customers
"""

# Comparing new customers and repeat customers
customer_orders = df.groupby('customer_id')['order_id'].count()

#Separate New & Repeat Customers
new_customers = (customer_orders == 1).sum()
repeat_customers = (customer_orders > 1).sum()

print("New Customers:", new_customers)
print("Repeat Customers:", repeat_customers)

"""Insights:
- Repeat customers indicate customer satisfaction and loyalty.
- High number of one-time customers may indicate churn risk.
- Business should focus on customer retention strategies.

6. Customer Segmentation
"""

# Analysing sales contribution from different customer segments
segment_sales = df.groupby('segment')['sales'].sum()

segment_sales

#Visualization
segment_sales.plot(kind='pie',
                   autopct='%1.1f%%',
                   figsize=(7,7))

plt.title('Sales by Customer Segment')

plt.show()

"""Insights:
- Consumer segment contributes significant sales revenue.
- Different customer segments show different purchasing behavior.
- Marketing campaigns can be customized for each segment.

7. High-Value Customers
"""

# Identifying customers contributing highest revenue
top_customers = df.groupby('customer_name')['sales'].sum().sort_values(ascending=False).head(10)

top_customers

#Visualization
top_customers.plot(kind='barh', figsize=(10,6))

plt.title('Top High-Value Customers')
plt.xlabel('Sales')

plt.show()

"""Insights:
- High-value customers contribute major business revenue.
- These customers should receive loyalty benefits and premium support.
- Retaining high-value customers is essential for business growth.

8. Churn Probability Indicators
"""

# Identifying customers with possible churn risk
churn_risk = customer_orders[customer_orders == 1]

print("Customers at Churn Risk:", len(churn_risk))

"""Insights:
- Customers with only one purchase may stop buying in future.
- Retention campaigns can help reduce churn rate.
- Personalized offers may improve repeat purchases.

###SECTION 3 — PRODUCT ANALYSIS
9. Fast-Moving Products
"""

# Identifying products sold in highest quantity
fast_products = df.groupby('product_name')['quantity'].sum().sort_values(ascending=False).head(10)

fast_products

#Visualization
fast_products.plot(kind='barh', figsize=(10,6))

plt.title('Fast Moving Products')
plt.xlabel('Quantity Sold')

plt.show()

"""Insights:
- Fast-moving products have consistently high demand.
- Business should maintain sufficient inventory for these products.
- These products can be prioritized in promotions and advertisements.

10. Dead Stock Items
"""

# Identifying products with very low sales
dead_stock = df.groupby('product_name')['sales'].sum().sort_values().head(10)

dead_stock

#Visualization
dead_stock.plot(kind='barh', figsize=(10,6))

plt.title('Dead Stock Products')
plt.xlabel('Sales')

plt.show()

"""Insights:
- Dead stock products contribute very little revenue.
- Excess inventory of these products increases storage cost.
- Business may consider discounts or discontinuation of such products.

11. High Return Categories
"""

# Analysing categories generating losses
loss_category = df[df['profit'] < 0]

high_loss_categories = loss_category.groupby('category')['profit'].sum()

high_loss_categories

#Visualization
high_loss_categories.plot(kind='bar', figsize=(8,5))

plt.title('High Loss Categories')
plt.ylabel('Loss')

plt.show()

"""Insights:
- Some categories are generating negative profits.
- High discounts may be reducing profitability.
- Pricing and discount strategies should be reviewed carefully.
"""

df.to_csv("cleaned_superstore_data.csv", index=False)

from google.colab import files
files.download("cleaned_superstore_data.csv")

"""Final Recommendations:
- Increase focus on high-performing regions and products.
- Improve retention strategies for repeat customers.
- Reduce excessive discounts on low-profit categories.
- Maintain stock for fast-moving products.
- Introduce targeted marketing campaigns for low-performing regions.
- Provide loyalty programs for high-value customers.

##Phase 5 — Sales Forecasting using Linear Regression
1. IMPORT REQUIRED LIBRARIES
"""

# Importing libraries for machine learning and visualization

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

"""2. CREATE MONTHLY SALES DATASET"""

# Creating monthly sales dataset

monthly_data = df.groupby('order_month')['sales'].sum().reset_index()

monthly_data

"""3. DEFINE FEATURES & TARGET"""

# Defining input and target variables

X = monthly_data[['order_month']]

y = monthly_data['sales']

print(X.head())
print(y.head())

"""4. CREATE & TRAIN MODEL"""

# Creating and training Linear Regression model

model = LinearRegression()

model.fit(X, y)

print("Model training completed successfully")

"""5. PREDICT SALES"""

# Predicting sales using trained model

predictions = model.predict(X)

predictions

"""6. EVALUATE MODEL PERFORMANCE"""

# Evaluating model performance

r2 = r2_score(y, predictions)

print("R2 Score:", r2)

"""7. PLOT ACTUAL VS PREDICTED SALES"""

# Visualizing actual vs predicted sales

plt.figure(figsize=(10,5))

# Actual Sales
plt.plot(monthly_data['order_month'],
         y,
         marker='o',
         linewidth=3,
         label='Actual Sales')

# Predicted Sales
plt.plot(monthly_data['order_month'],
         predictions,
         marker='o',
         linestyle='--',
         linewidth=3,
         label='Predicted Sales')

# Titles and labels
plt.title('Sales Forecasting using Linear Regression')

plt.xlabel('Month')

plt.ylabel('Sales')

# Showing legend
plt.legend()

# Grid
plt.grid(True)

# Display chart
plt.show()

"""Insights:

• The forecasting model predicts future sales trends based on historical monthly sales data.

• Sales show increasing trend during high-demand months.

• The predicted trend closely follows actual sales patterns.

• Predictive analytics can help businesses improve inventory and sales planning.
"""